# Generated by Django 2.2.11 on 2020-03-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swiped',
            unique_together={('uid', 'sid')},
        ),
    ]
