# Generated by Django 2.2.11 on 2020-03-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200312_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dating_gender',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性')], default='female', max_length=10, verbose_name='匹配的性别'),
        ),
    ]
